export interface Pillar {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  color: string;
}

export const PILLARS: Pillar[] = [
  {
    id: "disaster_response",
    name: "Disaster Response",
    description:
      "Rescue, relief, and rehabilitation during natural disasters and emergencies",
    keywords: [
      "disaster",
      "emergency",
      "relief",
      "hurricane",
      "flood",
      "wildfire",
      "earthquake",
      "tornado",
      "rescue",
      "FEMA",
      "rehabilitation",
      "storm",
      "evacuation",
      "shelter",
      "crisis",
      "recovery",
      "resilience",
      "preparedness",
      "first responder",
      "clean-up",
      "displaced",
      "humanitarian aid",
    ],
    color: "#DC2626",
  },
  {
    id: "education",
    name: "Education",
    description:
      "Academic support, literacy, after-school programs, and child sponsorship for underserved communities",
    keywords: [
      "education",
      "literacy",
      "after-school",
      "tutoring",
      "academic",
      "school",
      "learning",
      "STEM",
      "scholarship",
      "youth",
      "children",
      "student",
      "curriculum",
      "reading",
      "math",
      "college readiness",
      "K-12",
      "early childhood",
      "mentoring",
      "homework",
      "ESL",
      "language",
    ],
    color: "#2563EB",
  },
  {
    id: "family_services",
    name: "Family Services",
    description:
      "Health and wellness programs, family case management, and community support services",
    keywords: [
      "family",
      "health",
      "wellness",
      "diabetes",
      "nutrition",
      "mental health",
      "counseling",
      "case management",
      "social services",
      "community health",
      "preventive care",
      "senior",
      "elderly",
      "caregiver",
      "food assistance",
      "housing",
      "poverty",
      "vulnerable",
      "immigrant",
      "refugee",
    ],
    color: "#059669",
  },
  {
    id: "women_empowerment",
    name: "Women Empowerment",
    description:
      "Programs empowering women through skills development, health awareness, and economic opportunity",
    keywords: [
      "women",
      "gender",
      "empowerment",
      "maternal",
      "girls",
      "female",
      "domestic violence",
      "skills training",
      "entrepreneurship",
      "workforce development",
      "childcare",
      "reproductive health",
      "leadership",
      "equality",
      "economic opportunity",
      "self-sufficiency",
    ],
    color: "#9333EA",
  },
  {
    id: "volunteer_development",
    name: "Volunteer Development",
    description:
      "Mobilizing and training volunteers for community service and civic engagement",
    keywords: [
      "volunteer",
      "civic engagement",
      "community service",
      "capacity building",
      "AmeriCorps",
      "service learning",
      "internship",
      "training",
      "youth development",
      "leadership development",
      "mentorship",
      "nonprofit capacity",
      "community organizing",
    ],
    color: "#D97706",
  },
  {
    id: "policy_research",
    name: "Policy Research",
    description:
      "Research and advocacy on community issues affecting underserved populations",
    keywords: [
      "policy",
      "research",
      "advocacy",
      "data",
      "analysis",
      "community assessment",
      "survey",
      "impact evaluation",
      "social justice",
      "equity",
      "civil rights",
      "public policy",
      "think tank",
      "legislative",
    ],
    color: "#475569",
  },
];

export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
  "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
  "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
  "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
  "New Hampshire", "New Jersey", "New Mexico", "New York",
  "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
  "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
  "West Virginia", "Wisconsin", "Wyoming", "District of Columbia",
];
